import type { ProductData } from '@/lib/productUtils';

// Cart item with product reference and quantity
export interface CartItem {
  productId: string;          // Product 'd' tag identifier
  quantity: number;
  product: ProductData;       // Full product data for display
  addedAt: number;            // Timestamp for sorting
}

// Cart state
export interface CartState {
  items: CartItem[];
  updatedAt: number;
}

// Shipping information for checkout
export interface ShippingInfo {
  name: string;
  email: string;
  phone?: string;
  address: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  shippingZone: string;       // Shipping zone ID (uk, europe, worldwide)
  message?: string;           // Optional note to merchant
}

// Gamma Markets Kind 16 Order (Type 1) - Order creation
export interface GammaOrder {
  id: string;                 // UUID generated by customer
  type: 1;                    // Order creation type
  merchant: string;           // Merchant pubkey (hex)
  amount: number;             // Total in satoshis
  items: Array<{
    product_id: string;       // Product 'd' tag
    quantity: number;
  }>;
  shipping: ShippingInfo;
}

// Gamma Markets Kind 16 Payment Request (Type 2) - from merchant
export interface GammaPaymentRequest {
  id: string;                 // Order ID
  type: 2;
  amount: number;             // Amount in satoshis
  message?: string;
  payment_options: Array<{
    type: 'ln' | 'lnurl';
    link: string;             // BOLT11 invoice or LNURL
  }>;
}

// Gamma Markets Kind 16 Order Status (Type 3)
export interface GammaOrderStatus {
  id: string;                 // Order ID
  type: 3;
  message?: string;
  paid: boolean;
  shipped: boolean;
}

// Gamma Markets Kind 16 Shipping Info (Type 4)
export interface GammaShippingInfo {
  id: string;                 // Order ID
  type: 4;
  message?: string;
  tracking?: string;
  carrier?: string;
}

// Kind 17 Payment Receipt
export interface GammaPaymentReceipt {
  order_id: string;
  type: 'ln';
  proof: string;              // Lightning preimage
}

// Checkout state
export interface CheckoutState {
  orderId: string | null;
  status: 'idle' | 'submitting' | 'awaiting_payment' | 'paid' | 'shipped' | 'error';
  error?: string;
  paymentRequest?: GammaPaymentRequest;
}
